version: "3.8"
services:
  
  db:
    image: postgres:alpine
    ports: 
      - ${DB_PORT}:5432
    environment: 
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    restart: always
    
  authDB:
    image: mongo:latest
    ports: 
      - ${AUTH_DB_PORT}:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: "${AUTH_DB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${AUTH_DB_PASSWORD}"
    restart: always

  web:
    build: .
    ports: 
      - ${API_PORT}:8080
    depends_on: 
      - db
      - authDB
    environment: 
      MODE: "${MODE}"
      API_PORT: ${API_PORT} 
      DB_PORT: ${DB_PORT} 
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}" 
      DB_NAME: "${DB_NAME}"
      AUTH_DB_HOST: "${AUTH_DB_HOST}"
      AUTH_DB_USER: "${AUTH_DB_USER}"
      AUTH_DB_PASSWORD: "${AUTH_DB_PASSWORD}"
      AUTH_DB_PORT: "${AUTH_DB_PORT}"
      AUTH_DB_NAME: "${AUTH_DB_NAME}"
      JWT_SALT: "${JWT_SALT}"
    restart: always